### ISSUE TITLE
Latest patch crash problems

### ISSUE THREAD

**Issue by SirHaesslich** [ShikiSeiren/NecroMod#11]
I really like the character despite it feeling slightly broken(I mean I like winning and some combos are absurdly epic, so fck it:D), and I continue playing him despite already running into two crash-inducing bugs dodging which does handicap the gameplay slightly.
1) when trying to spread the Lifebind debuff from one enemy to all others using the Epidemy card, game crashes, tried twice with same results(it was the Exordium AoE-heavy fight, either 3 Louses, 4 Grems or 5 Slimes so that was the only way to make it alive out of it)
2) when applying the Bone Cage to the enemy who does not intend to attack, the game crashes(why did I do it? First time, I wanted to reshuffle it into the deck from the Exhaust pile for future use, then I had a Runic Dome and had no idea who is gonna attack me and who is not). The bug triggered several times on various enemies, I doubt it is enemy-dependent at all.

Hope you will find a way to fix it, I like the mod and would love to see it progress

**Comment by SirHaesslich** [comment]
Update for the Bone Cage one, I managed to catch the crash log, if that helps

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoClassDefFoundError: com/megacrit/cardcrawl/actions/unique/OpeningAction
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoClassDefFoundError: com/megacrit/cardcrawl/actions/unique/OpeningAction
	at necromod.cards.Bone_Prison.use(Bone_Prison.java:53)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:923)
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:261)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:145)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:250)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2574)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:778)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:371)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.ClassNotFoundException: com.megacrit.cardcrawl.actions.unique.OpeningAction
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:65)
	... 10 more
