### ISSUE TITLE
Can't load mod

### ISSUE THREAD

**Issue by Unexplnednachos** [ShikiSeiren/NecroMod#7]
Hey when I try to load the mod, I get the following error from modthespire:

Exception in thread "Thread-1" java.lang.NoSuchMethodError: sun.reflect.ReflectionFactory.newConstructorAccessor(Ljava/lang/reflect/Constructor;)Lsun/reflect/ConstructorAccessor;
	at com.evacipated.cardcrawl.modthespire.EnumBusterReflect.findConstructorAccessor(EnumBusterReflect.java:211)
	at com.evacipated.cardcrawl.modthespire.EnumBusterReflect.make(EnumBusterReflect.java:70)
	at com.evacipated.cardcrawl.modthespire.EnumBusterReflect.make(EnumBusterReflect.java:49)
	at com.evacipated.cardcrawl.modthespire.Patcher.patchEnums(Patcher.java:105)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:159)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:181)
	at java.base/java.lang.Thread.run(Unknown Source)

I have BaseMod loading first as well.  Any ideas on how to get it working?

**Comment by Meow-Mixer** [comment]
That happens when steam tries to load its panel. You bypass it with the
shortcut for modloader provided by the installation.
